#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace ABP_Astronaut_PP { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_MecMortFront { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_MecMortBack { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Head { struct FAnimBlueprintGeneratedConstantData; }


namespace CR_Astronaut_Aim
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace CR_Astronaut_PP
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace CR_Astronaut_HandsAim
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace ABP_Astronaut_Hands
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Astronaut_Body
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Tuto_Mannequin
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
