#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// LockdownProtocol
// 5.2.1-26001984+++UE5+Release-5.2

// Includes the entire SDK, include files directly for faster compilation!
#define IM_PI                           3.14159265358979323846f
#include "SDK/Basic.hpp"
#include "SDK/CoreUObject_structs.hpp"
#include "SDK/CoreUObject_classes.hpp"
#include "SDK/Chaos_structs.hpp"
#include "SDK/InputCore_structs.hpp"
#include "SDK/Slate_structs.hpp"
#include "SDK/PhysicsCore_structs.hpp"
#include "SDK/Engine_structs.hpp"
#include "SDK/W_Rules_classes.hpp"
#include "SDK/AnimationCore_structs.hpp"
#include "SDK/RigVM_structs.hpp"
#include "SDK/MovieScene_structs.hpp"
#include "SDK/Constraints_structs.hpp"
#include "SDK/ControlRig_structs.hpp"
#include "SDK/AnimGraphRuntime_structs.hpp"
#include "SDK/MovieSceneTracks_structs.hpp"
#include "SDK/MovieScene_classes.hpp"
#include "SDK/AudioExtensions_structs.hpp"
#include "SDK/AudioExtensions_classes.hpp"
#include "SDK/PhysicsCore_classes.hpp"
#include "SDK/DeveloperSettings_structs.hpp"
#include "SDK/DeveloperSettings_classes.hpp"
#include "SDK/AudioPlatformConfiguration_structs.hpp"
#include "SDK/SlateCore_structs.hpp"
#include "SDK/NetCore_structs.hpp"
#include "SDK/NetCore_classes.hpp"
#include "SDK/Engine_classes.hpp"
#include "SDK/MovieSceneTracks_classes.hpp"
#include "SDK/Constraints_classes.hpp"
#include "SDK/ControlRig_classes.hpp"
#include "SDK/RigVM_classes.hpp"
#include "SDK/LevelSequence_structs.hpp"
#include "SDK/LevelSequence_classes.hpp"
#include "SDK/MovieSceneCapture_structs.hpp"
#include "SDK/ImageWriteQueue_structs.hpp"
#include "SDK/MovieSceneCapture_classes.hpp"
#include "SDK/SequencerScripting_structs.hpp"
#include "SDK/SequencerScripting_classes.hpp"
#include "SDK/PacketHandler_classes.hpp"
#include "SDK/OnlineSubsystemSteamCore_classes.hpp"
#include "SDK/OnlineSubsystemUtils_structs.hpp"
#include "SDK/OnlineSubsystem_structs.hpp"
#include "SDK/OnlineSubsystemUtils_classes.hpp"
#include "SDK/SteamCorePro_structs.hpp"
#include "SDK/SteamCoreShared_structs.hpp"
#include "SDK/SteamCorePro_classes.hpp"
#include "SDK/SteamCoreSockets_classes.hpp"
#include "SDK/OnlineSubsystem_classes.hpp"
#include "SDK/AudioMixer_structs.hpp"
#include "SDK/AudioMixer_classes.hpp"
#include "SDK/SteamAudio_structs.hpp"
#include "SDK/SteamAudio_classes.hpp"
#include "SDK/Str_ItemState_structs.hpp"
#include "SDK/W_ProcessedRequest_classes.hpp"
#include "SDK/Reflex_structs.hpp"
#include "SDK/Reflex_classes.hpp"
#include "SDK/FileToolkitX_classes.hpp"
#include "SDK/RuntimeDataTable_structs.hpp"
#include "SDK/EasyCsv_structs.hpp"
#include "SDK/RuntimeDataTable_classes.hpp"
#include "SDK/EasyCsv_classes.hpp"
#include "SDK/AsyncTickPhysics_classes.hpp"
#include "SDK/Paper2D_structs.hpp"
#include "SDK/Paper2D_classes.hpp"
#include "SDK/IKRig_structs.hpp"
#include "SDK/PBIK_structs.hpp"
#include "SDK/IKRig_classes.hpp"
#include "SDK/GameplayCameras_structs.hpp"
#include "SDK/GameplayCameras_classes.hpp"
#include "SDK/W_Player_List_classes.hpp"
#include "SDK/TemplateSequence_structs.hpp"
#include "SDK/CinematicCamera_structs.hpp"
#include "SDK/TemplateSequence_classes.hpp"
#include "SDK/OodleNetworkHandlerComponent_structs.hpp"
#include "SDK/OodleNetworkHandlerComponent_classes.hpp"
#include "SDK/AnimationSharing_structs.hpp"
#include "SDK/AnimationSharing_classes.hpp"
#include "SDK/SignificanceManager_classes.hpp"
#include "SDK/ChaosCaching_structs.hpp"
#include "SDK/ChaosCaching_classes.hpp"
#include "SDK/UObjectPlugin_structs.hpp"
#include "SDK/UObjectPlugin_classes.hpp"
#include "SDK/FacialAnimation_classes.hpp"
#include "SDK/EnhancedInput_structs.hpp"
#include "SDK/EnhancedInput_classes.hpp"
#include "SDK/E_ColorsRepartition_structs.hpp"
#include "SDK/DatasmithContent_structs.hpp"
#include "SDK/DatasmithContent_classes.hpp"
#include "SDK/VariantManagerContent_structs.hpp"
#include "SDK/VariantManagerContent_classes.hpp"
#include "SDK/GLTFExporter_structs.hpp"
#include "SDK/GLTFExporter_classes.hpp"
#include "SDK/AutomationUtils_classes.hpp"
#include "SDK/W_DataPC_Message_UI_classes.hpp"
#include "SDK/ClothingSystemRuntimeInterface_structs.hpp"
#include "SDK/ClothingSystemRuntimeInterface_classes.hpp"
#include "SDK/ClothingSystemRuntimeCommon_structs.hpp"
#include "SDK/ClothingSystemRuntimeCommon_classes.hpp"
#include "SDK/ChaosCloth_structs.hpp"
#include "SDK/ChaosCloth_classes.hpp"
#include "SDK/TakeMovieScene_classes.hpp"
#include "SDK/GeometryCollectionTracks_structs.hpp"
#include "SDK/GeometryCollectionTracks_classes.hpp"
#include "SDK/ProceduralMeshComponent_structs.hpp"
#include "SDK/ProceduralMeshComponent_classes.hpp"
#include "SDK/DataflowEnginePlugin_classes.hpp"
#include "SDK/NiagaraCore_structs.hpp"
#include "SDK/NiagaraCore_classes.hpp"
#include "SDK/NiagaraShader_structs.hpp"
#include "SDK/Niagara_structs.hpp"
#include "SDK/NiagaraShader_classes.hpp"
#include "SDK/Niagara_classes.hpp"
#include "SDK/ChaosNiagara_structs.hpp"
#include "SDK/ChaosNiagara_classes.hpp"
#include "SDK/NiagaraAnimNotifies_structs.hpp"
#include "SDK/NiagaraAnimNotifies_classes.hpp"
#include "SDK/GeometryCache_structs.hpp"
#include "SDK/GeometryCache_classes.hpp"
#include "SDK/W_SelectorPart_classes.hpp"
#include "SDK/GeometryCacheTracks_structs.hpp"
#include "SDK/GeometryCacheTracks_classes.hpp"
#include "SDK/GS_classes.hpp"
#include "SDK/AvfMediaFactory_classes.hpp"
#include "SDK/Enum_AudioSAS_structs.hpp"
#include "SDK/MediaAssets_structs.hpp"
#include "SDK/MediaAssets_classes.hpp"
#include "SDK/ImgMedia_structs.hpp"
#include "SDK/ImgMedia_classes.hpp"
#include "SDK/ImgMediaEngine_classes.hpp"
#include "SDK/ImgMediaFactory_classes.hpp"
#include "SDK/CoreOnline_structs.hpp"
#include "SDK/MediaCompositing_structs.hpp"
#include "SDK/MediaCompositing_classes.hpp"
#include "SDK/MediaPlate_structs.hpp"
#include "SDK/MediaPlate_classes.hpp"
#include "SDK/WmfMediaFactory_classes.hpp"
#include "SDK/TcpMessaging_classes.hpp"
#include "SDK/UdpMessaging_structs.hpp"
#include "SDK/UdpMessaging_classes.hpp"
#include "SDK/ActorSequence_structs.hpp"
#include "SDK/ActorSequence_classes.hpp"
#include "SDK/ActorLayerUtilities_structs.hpp"
#include "SDK/ActorLayerUtilities_classes.hpp"
#include "SDK/AndroidFileServer_structs.hpp"
#include "SDK/AndroidFileServer_classes.hpp"
#include "SDK/E_ConsumableType_structs.hpp"
#include "SDK/Data_Consumable_classes.hpp"
#include "SDK/AndroidPermission_classes.hpp"
#include "SDK/AppleImageUtils_structs.hpp"
#include "SDK/AppleImageUtils_classes.hpp"
#include "SDK/ArchVisCharacter_classes.hpp"
#include "SDK/GameplayTags_structs.hpp"
#include "SDK/GameplayTags_classes.hpp"
#include "SDK/AssetTags_structs.hpp"
#include "SDK/AssetTags_classes.hpp"
#include "SDK/Data_MeleeType_classes.hpp"
#include "SDK/AudioCapture_structs.hpp"
#include "SDK/AudioCapture_classes.hpp"
#include "SDK/CableComponent_classes.hpp"
#include "SDK/CustomMeshComponent_structs.hpp"
#include "SDK/CustomMeshComponent_classes.hpp"
#include "SDK/GooglePAD_structs.hpp"
#include "SDK/GooglePAD_classes.hpp"
#include "SDK/LocationServicesBPLibrary_structs.hpp"
#include "SDK/LocationServicesBPLibrary_classes.hpp"
#include "SDK/MetasoundFrontend_structs.hpp"
#include "SDK/MetasoundFrontend_classes.hpp"
#include "SDK/MetasoundEngine_structs.hpp"
#include "SDK/MetasoundEngine_classes.hpp"
#include "SDK/ABP_Astronaut_PP_structs.hpp"
#include "SDK/ABP_Astronaut_PP_classes.hpp"
#include "SDK/UMG_structs.hpp"
#include "SDK/UMG_classes.hpp"
#include "SDK/AudioWidgets_structs.hpp"
#include "SDK/AudioWidgets_classes.hpp"
#include "SDK/AudioAnalyzer_classes.hpp"
#include "SDK/AudioSynesthesia_structs.hpp"
#include "SDK/AudioSynesthesia_classes.hpp"
#include "SDK/WaveTable_structs.hpp"
#include "SDK/WaveTable_classes.hpp"
#include "SDK/MobilePatchingUtils_classes.hpp"
#include "SDK/BP_WallText_classes.hpp"
#include "SDK/SoundFields_classes.hpp"
#include "SDK/Synthesis_structs.hpp"
#include "SDK/Synthesis_classes.hpp"
#include "SDK/TraceUtilities_classes.hpp"
#include "SDK/AnimationCore_classes.hpp"
#include "SDK/W_GI_HUD_classes.hpp"
#include "SDK/InputCore_classes.hpp"
#include "SDK/SlateCore_classes.hpp"
#include "SDK/Slate_classes.hpp"
#include "SDK/CR_Astronaut_PP_classes.hpp"
#include "SDK/ImageWriteQueue_classes.hpp"
#include "SDK/Str_TutorialRoom_structs.hpp"
#include "SDK/MaterialShaderQualitySettings_structs.hpp"
#include "SDK/MaterialShaderQualitySettings_classes.hpp"
#include "SDK/EyeTracker_structs.hpp"
#include "SDK/EyeTracker_classes.hpp"
#include "SDK/Renderer_classes.hpp"
#include "SDK/EngineSettings_structs.hpp"
#include "SDK/EngineSettings_classes.hpp"
#include "SDK/MRMesh_structs.hpp"
#include "SDK/MRMesh_classes.hpp"
#include "SDK/E_PizzaMachine_State_structs.hpp"
#include "SDK/AugmentedReality_structs.hpp"
#include "SDK/AugmentedReality_classes.hpp"
#include "SDK/HeadMountedDisplay_structs.hpp"
#include "SDK/HeadMountedDisplay_classes.hpp"
#include "SDK/BuildPatchServices_structs.hpp"
#include "SDK/BuildPatchServices_classes.hpp"
#include "SDK/TypedElementFramework_structs.hpp"
#include "SDK/TypedElementFramework_classes.hpp"
#include "SDK/Foliage_structs.hpp"
#include "SDK/Foliage_classes.hpp"
#include "SDK/Landscape_structs.hpp"
#include "SDK/Landscape_classes.hpp"
#include "SDK/TimeManagement_structs.hpp"
#include "SDK/TimeManagement_classes.hpp"
#include "SDK/MeshDescription_structs.hpp"
#include "SDK/MeshDescription_classes.hpp"
#include "SDK/StaticMeshDescription_structs.hpp"
#include "SDK/StaticMeshDescription_classes.hpp"
#include "SDK/ChaosSolverEngine_structs.hpp"
#include "SDK/ChaosSolverEngine_classes.hpp"
#include "SDK/FieldSystemEngine_structs.hpp"
#include "SDK/FieldSystemEngine_classes.hpp"
#include "SDK/DataflowCore_structs.hpp"
#include "SDK/DataflowCore_classes.hpp"
#include "SDK/DataflowEngine_structs.hpp"
#include "SDK/DataflowEngine_classes.hpp"
#include "SDK/GeometryCollectionEngine_structs.hpp"
#include "SDK/GeometryCollectionEngine_classes.hpp"
#include "SDK/AnimGraphRuntime_classes.hpp"
#include "SDK/PropertyPath_structs.hpp"
#include "SDK/PropertyPath_classes.hpp"
#include "SDK/TypedElementRuntime_structs.hpp"
#include "SDK/TypedElementRuntime_classes.hpp"
#include "SDK/CinematicCamera_classes.hpp"
#include "SDK/AudioLinkCore_classes.hpp"
#include "SDK/AudioLinkEngine_classes.hpp"
#include "SDK/JsonUtilities_structs.hpp"
#include "SDK/JsonUtilities_classes.hpp"
#include "SDK/Enum_SelectedColor_structs.hpp"
#include "SDK/AssetRegistry_structs.hpp"
#include "SDK/AssetRegistry_classes.hpp"
#include "SDK/IrisCore_structs.hpp"
#include "SDK/IrisCore_classes.hpp"
#include "SDK/MoviePlayer_structs.hpp"
#include "SDK/MoviePlayer_classes.hpp"
#include "SDK/Overlay_structs.hpp"
#include "SDK/Overlay_classes.hpp"
#include "SDK/ClothingSystemRuntimeNv_structs.hpp"
#include "SDK/ClothingSystemRuntimeNv_classes.hpp"
#include "SDK/NavigationSystem_structs.hpp"
#include "SDK/NavigationSystem_classes.hpp"
#include "SDK/GameplayTasks_structs.hpp"
#include "SDK/GameplayTasks_classes.hpp"
#include "SDK/AIModule_structs.hpp"
#include "SDK/AIModule_classes.hpp"
#include "SDK/W_InputsSettings_classes.hpp"
#include "SDK/InteractiveToolsFramework_structs.hpp"
#include "SDK/InteractiveToolsFramework_classes.hpp"
#include "SDK/GeometryFramework_structs.hpp"
#include "SDK/GeometryFramework_classes.hpp"
#include "SDK/AdvancedWidgets_classes.hpp"
#include "SDK/ControlRigSpline_structs.hpp"
#include "SDK/FullBodyIK_structs.hpp"
#include "SDK/TutoSprintJauge_classes.hpp"
#include "SDK/GeometryCollectionNodes_structs.hpp"
#include "SDK/Tuto_Button_classes.hpp"
#include "SDK/E_PlayerRole_structs.hpp"
#include "SDK/MediaUtils_structs.hpp"
#include "SDK/LocalFileNetworkReplayStreaming_structs.hpp"
#include "SDK/HttpNetworkReplayStreaming_structs.hpp"
#include "SDK/VectorVM_structs.hpp"
#include "SDK/DataflowNodes_structs.hpp"
#include "SDK/EngineMessages_structs.hpp"
#include "SDK/Serialization_structs.hpp"
#include "SDK/Scanner_Machine_classes.hpp"
#include "SDK/SessionMessages_structs.hpp"
#include "SDK/DmgTypeBP_Environmental_classes.hpp"
#include "SDK/W_Switcher_classes.hpp"
#include "SDK/Transient_structs.hpp"
#include "SDK/E_ItemImpactType_structs.hpp"
#include "SDK/W_WeaponParameter_classes.hpp"
#include "SDK/Enum_Sectors_structs.hpp"
#include "SDK/Enum_TutoMannequinState_structs.hpp"
#include "SDK/Tuto_Mannequin_classes.hpp"
#include "SDK/Str_ItemSpawnRequest_structs.hpp"
#include "SDK/Str_ItemSpawnLocation_structs.hpp"
#include "SDK/E_Logic_structs.hpp"
#include "SDK/Enum_MoveInputState_structs.hpp"
#include "SDK/W_UpperNotif_classes.hpp"
#include "SDK/E_Alim_FuzeState_structs.hpp"
#include "SDK/E_ContainerSlot_State_structs.hpp"
#include "SDK/Enum_DamageType_structs.hpp"
#include "SDK/E_ItemPlaceType_structs.hpp"
#include "SDK/GraphicSettings_structs.hpp"
#include "SDK/E_ItemType_structs.hpp"
#include "SDK/W_PlayerDoorInfo_classes.hpp"
#include "SDK/W_TaskList_classes.hpp"
#include "SDK/Enum_SkinElement_structs.hpp"
#include "SDK/Data_Skin_Element_classes.hpp"
#include "SDK/Str_Skin_List_structs.hpp"
#include "SDK/Discord_Plane_Blueprint_classes.hpp"
#include "SDK/CR_Astronaut_Aim_classes.hpp"
#include "SDK/W_MainNotif_classes.hpp"
#include "SDK/E_DataPC_State_structs.hpp"
#include "SDK/Str_GunSettings_structs.hpp"
#include "SDK/W_DataPC_Underscore_UI_classes.hpp"
#include "SDK/Str_Skin_Skin_structs.hpp"
#include "SDK/W_MachinePannelScreen_classes.hpp"
#include "SDK/W_MapDot_classes.hpp"
#include "SDK/Data_ItemThrowType_classes.hpp"
#include "SDK/InputSettings_structs.hpp"
#include "SDK/Enum_Stance_structs.hpp"
#include "SDK/AudioSettings_structs.hpp"
#include "SDK/Enum_PathLevel_structs.hpp"
#include "SDK/Data_Player_classes.hpp"
#include "SDK/E_Difficulty_structs.hpp"
#include "SDK/ABP_MecMortFront_structs.hpp"
#include "SDK/ABP_MecMortFront_classes.hpp"
#include "SDK/E_SessionState_structs.hpp"
#include "SDK/Tutorial_Screen_classes.hpp"
#include "SDK/E_GenericMachine_State_structs.hpp"
#include "SDK/GamepadSettings_structs.hpp"
#include "SDK/Str_ActionTarget_structs.hpp"
#include "SDK/PlayerSpawn_classes.hpp"
#include "SDK/Task_Pizzushi_classes.hpp"
#include "SDK/E_ShotPattern_structs.hpp"
#include "SDK/FunctionLibrary_classes.hpp"
#include "SDK/Str_MusicToPlay_structs.hpp"
#include "SDK/Enum_Corner_structs.hpp"
#include "SDK/E_InputMode_structs.hpp"
#include "SDK/Enum_AudioRoom_structs.hpp"
#include "SDK/E_ContainerSlot_Position_structs.hpp"
#include "SDK/E_AnalysisPC_State_structs.hpp"
#include "SDK/Save_BanList_classes.hpp"
#include "SDK/E_VentState_structs.hpp"
#include "SDK/CR_Astronaut_HandsAim_classes.hpp"
#include "SDK/ReflectionHandler_classes.hpp"
#include "SDK/Tuto_ItemSquare_classes.hpp"
#include "SDK/W_UpperScreen_classes.hpp"
#include "SDK/Str_SkinMaterial_structs.hpp"
#include "SDK/TaskManager_classes.hpp"
#include "SDK/W_Rice_Screen_classes.hpp"
#include "SDK/W_DataPC_UI_classes.hpp"
#include "SDK/Save_Settings_classes.hpp"
#include "SDK/W_CameraSector_classes.hpp"
#include "SDK/W_NameLine_classes.hpp"
#include "SDK/Data_Face_classes.hpp"
#include "SDK/W_AnalysisPC_UI_classes.hpp"
#include "SDK/Data_Skin_Body_classes.hpp"
#include "SDK/ABP_MecMortBack_structs.hpp"
#include "SDK/ABP_MecMortBack_classes.hpp"
#include "SDK/Analysis_PC_classes.hpp"
#include "SDK/Data_Skin_Ghost_classes.hpp"
#include "SDK/Data_Skin_Head_classes.hpp"
#include "SDK/W_GenericMachine_Jauge_classes.hpp"
#include "SDK/W_Slider_classes.hpp"
#include "SDK/W_Battery_Jauge_classes.hpp"
#include "SDK/W_TutoScreeWorld_classes.hpp"
#include "SDK/W_Interaction_classes.hpp"
#include "SDK/W_Menu_classes.hpp"
#include "SDK/Str_SkinSet_structs.hpp"
#include "SDK/W_Bannier_classes.hpp"
#include "SDK/WeaponFX_classes.hpp"
#include "SDK/Data_Item_classes.hpp"
#include "SDK/Data_Gun_classes.hpp"
#include "SDK/Data_Melee_classes.hpp"
#include "SDK/Str_Item_structs.hpp"
#include "SDK/Mec_SkinViewer_classes.hpp"
#include "SDK/Save_Skin_classes.hpp"
#include "SDK/ItemDynamicMesh_classes.hpp"
#include "SDK/Mec_classes.hpp"
#include "SDK/ABP_Head_structs.hpp"
#include "SDK/ABP_Head_classes.hpp"
#include "SDK/ABP_Astronaut_Hands_structs.hpp"
#include "SDK/ABP_Astronaut_Hands_classes.hpp"
#include "SDK/Str_ColorLink_structs.hpp"
#include "SDK/GM_classes.hpp"
#include "SDK/W_InputInfo_classes.hpp"
#include "SDK/W_SecondaryInfo_classes.hpp"
#include "SDK/W_Crosshair_classes.hpp"
#include "SDK/W_ItemStats_classes.hpp"
#include "SDK/W_Inventory_classes.hpp"
#include "SDK/W_Ammo_classes.hpp"
#include "SDK/SoundSource_classes.hpp"
#include "SDK/Button_classes.hpp"
#include "SDK/WorldItem_classes.hpp"
#include "SDK/SoundPath_classes.hpp"
#include "SDK/Buff_classes.hpp"
#include "SDK/BPI_Interaction_classes.hpp"
#include "SDK/VoiceSource_classes.hpp"
#include "SDK/WaterCamera_classes.hpp"
#include "SDK/MainGI_classes.hpp"
#include "SDK/W_BottumScreen_classes.hpp"
#include "SDK/BulletTravel_classes.hpp"
#include "SDK/PlayerDoor_classes.hpp"
#include "SDK/TaskKeyboard_classes.hpp"
#include "SDK/Item_Spawner_classes.hpp"
#include "SDK/BulletImpact_classes.hpp"
#include "SDK/Explosion_classes.hpp"
#include "SDK/W_Buff_classes.hpp"
#include "SDK/Tuto_Check_classes.hpp"
#include "SDK/Interaction_classes.hpp"
#include "SDK/W_WeaponSetting_classes.hpp"
#include "SDK/BPL_Items_classes.hpp"
#include "SDK/PC_classes.hpp"
#include "SDK/Str_ItemSpawnRef_structs.hpp"
#include "SDK/W_PlayerState_classes.hpp"
#include "SDK/ABP_Astronaut_Body_structs.hpp"
#include "SDK/ABP_Astronaut_Body_classes.hpp"
#include "SDK/Screw_classes.hpp"
#include "SDK/ItemSlot_classes.hpp"
#include "SDK/Plant_classes.hpp"
#include "SDK/W_SettingMenu_classes.hpp"
#include "SDK/Item_classes.hpp"
#include "SDK/W_Trigger_classes.hpp"
#include "SDK/W_PlayersInfo_classes.hpp"
#include "SDK/W_GameInfo_classes.hpp"
#include "SDK/W_DebugSpawnItem_classes.hpp"
#include "SDK/ItemSpawn_Handler_classes.hpp"
#include "SDK/ABP_Tuto_Mannequin_structs.hpp"
#include "SDK/ABP_Tuto_Mannequin_classes.hpp"
#include "SDK/Vent_classes.hpp"
#include "SDK/SampleSlot_classes.hpp"
#include "SDK/ContainerSlot_classes.hpp"
#include "SDK/FilterCleaner_classes.hpp"
#include "SDK/BottleSlot_classes.hpp"
#include "SDK/Data_PC_classes.hpp"
#include "SDK/W_Button_classes.hpp"
#include "SDK/W_BarPart_classes.hpp"
#include "SDK/W_DebugSpawner_classes.hpp"
#include "SDK/DeliveryCase_classes.hpp"
#include "SDK/Task_classes.hpp"
#include "SDK/AlimBox_classes.hpp"
#include "SDK/Mixer_classes.hpp"
#include "SDK/Centrifuge_classes.hpp"
#include "SDK/MachinePannel_classes.hpp"
#include "SDK/W_AudioSettings_classes.hpp"
#include "SDK/W_KeyMap_classes.hpp"
#include "SDK/W_PlayerFromList_classes.hpp"
#include "SDK/W_SessionMenu_2_classes.hpp"
#include "SDK/W_Selector_classes.hpp"
#include "SDK/W_MainBar_classes.hpp"
#include "SDK/W_Tablet_UI_classes.hpp"
#include "SDK/Task_Vents_classes.hpp"
#include "SDK/Task_PlantAnalysis_classes.hpp"
#include "SDK/Task_Data_classes.hpp"
#include "SDK/Task_DelivryIn_classes.hpp"
#include "SDK/Task_Machine_classes.hpp"
#include "SDK/W_BlackList_classes.hpp"
#include "SDK/W_GamepadSettings_classes.hpp"
#include "SDK/W_GraphicSettings_classes.hpp"
#include "SDK/Tablet_classes.hpp"
#include "SDK/W_GhostTaskFromList_classes.hpp"
#include "SDK/W_Tablet_Trigger_classes.hpp"
#include "SDK/W_TaskMap2_classes.hpp"
#include "SDK/W_BodyTablet_UI_classes.hpp"
#include "SDK/Analyzer_classes.hpp"
#include "SDK/W_Skin_SkinSelection_classes.hpp"
#include "SDK/W_Skin_ColorSelection_classes.hpp"
#include "SDK/W_Tablet_ButtonVideo_classes.hpp"
#include "SDK/W_Tablet_ButtonText_classes.hpp"
#include "SDK/W_Skin_CharacterSelection_classes.hpp"
#include "SDK/W_TaskFromList_classes.hpp"
#include "SDK/BodyTablet_classes.hpp"
#include "SDK/W_CustomMenuTabButton_classes.hpp"
#include "SDK/W_Tablet_PlayerFromList_classes.hpp"
#include "SDK/W_Tablet_Friend_classes.hpp"
#include "SDK/W_TaskTutorialButton_classes.hpp"
#include "SDK/W_Tablet_Server_classes.hpp"
#include "SDK/W_Tablet_TaskSetting_classes.hpp"
#include "SDK/W_Tablet_SessionSetting_classes.hpp"
#include "SDK/W_GhostTaskList_classes.hpp"
#include "SDK/W_TaskInfo_classes.hpp"
#include "SDK/W_CustomMenuTabs_classes.hpp"
#include "SDK/W_inGame_classes.hpp"
#include "SDK/CustomPlanarReflection_classes.hpp"
#include "SDK/Enum_MusicLoudness_structs.hpp"
#include "SDK/E_RiceMachine_State_structs.hpp"
#include "SDK/W_MusicPlayerScreen_classes.hpp"
#include "SDK/BP_MapInteractive_Aquarium_classes.hpp"
#include "SDK/Tuto_Door_classes.hpp"
#include "SDK/Tuto_SwitchSquare_classes.hpp"
#include "SDK/Task_Alim_classes.hpp"
#include "SDK/Tuto_Screw_classes.hpp"
#include "SDK/Tuto_ItemSpawn_classes.hpp"
#include "SDK/Tuto_AlimBox_classes.hpp"
#include "SDK/CamerasStack_structs.hpp"
#include "SDK/PC_Cameras_classes.hpp"
#include "SDK/CameraRoomHandler_classes.hpp"
#include "SDK/PC_tuto_classes.hpp"
#include "SDK/W_ScannerUpdate_UI_classes.hpp"
#include "SDK/W_Pizzusshi_Screen_classes.hpp"
#include "SDK/W_Scanner_TargetDot_classes.hpp"
#include "SDK/Music_Small_classes.hpp"
#include "SDK/Tuto_SneakSquare_classes.hpp"
#include "SDK/Tuto_HandsSquare_classes.hpp"
#include "SDK/Scanner_PC_classes.hpp"
#include "SDK/ContainerCleaner_classes.hpp"
#include "SDK/W_TutorialSelection_classes.hpp"
#include "SDK/Str_ScannerDot_structs.hpp"
#include "SDK/Fish_Machine_classes.hpp"
#include "SDK/Rice_Machine_classes.hpp"
#include "SDK/TutoManager_classes.hpp"
#include "SDK/W_TutoPC_UI_classes.hpp"
#include "SDK/BP_groundMarking_classes.hpp"
#include "SDK/RoomCamera_classes.hpp"
#include "SDK/BatteryCharger_classes.hpp"
#include "SDK/Pizzushi_Machine_classes.hpp"
#include "SDK/Pizzushi_Table_classes.hpp"
#include "SDK/Scanner_Screen_classes.hpp"
#include "SDK/CameraScreen_classes.hpp"
#include "SDK/Task_Scanner_classes.hpp"
#include "SDK/W_CameraPC_UI_classes.hpp"
#include "SDK/EditorRender_classes.hpp"

class unrealengine {
public:
	static inline SDK::UWorld* GWorld = NULL;
	static inline PBYTE GObjects = NULL;
	static inline SDK::UWorld* World = NULL;
	static inline SDK::ACharacter* me = NULL;
	//static inline SDK::APawn* PrivateMy = NULL;


	//
	static inline SDK::UGameInstance* GameInstance = NULL;
	static inline SDK::ULocalPlayer* LocalPlayer = NULL;
	static inline SDK::APlayerController* LocalPlayerController = NULL;
	static inline SDK::APlayerState* PlayerState = NULL;
	static inline SDK::APlayerCameraManager* PlayerCameraManager = NULL;
	static inline SDK::APawn* LocalPawn = NULL;
	static inline SDK::USceneComponent* RootComponent = NULL;
	static inline SDK::AGameStateBase* GameState = NULL;

	bool bFov = false;
	float Fov = 0.f;
	float Smoothing = 1.f;
	SDK::FVector2D w2c(SDK::FVector location)
	{
		SDK::FVector2D screen;
		SDK::UWorld* World = GWorld;
		SDK::APlayerController* playerController = World->OwningGameInstance->LocalPlayers[0]->PlayerController;

		if (playerController)
		{
			playerController->ProjectWorldLocationToScreen(location, &screen, false);
			return screen;
		}

		return { 0,0 };
	}

	__forceinline float SmoothOutYaw(float targetYaw, float currentYaw, float smoothness)
	{
		if (targetYaw > 0.f && currentYaw < 0.f)
		{
			float dist = 180.f - targetYaw + 180.f + currentYaw;
			if (dist < 180.f)
				return currentYaw - dist / smoothness;
		}
		else if (currentYaw > 0.f && targetYaw < 0.f)
		{
			float dist = 180.f - currentYaw + 180.f + targetYaw;
			if (dist < 180.f)
				return currentYaw + dist / smoothness;
		}

		return currentYaw + (targetYaw - currentYaw) / smoothness;
	}

	//SDK::FRotator CalcAngle(const SDK::FVector& src, const SDK::FVector& dst, const SDK::FRotator currentAngles, float smoothness)
	//{
	//	SDK::FVector delta = dst - src;

	//	float dist = sqrtf(delta.X * delta.X + delta.Y * delta.Y + delta.Z * delta.Z);
	//	float pitch = (-((acosf((delta.Z / dist)) * 180.0f / IM_PI) - 90.0f));
	//	float yaw = atan2f(delta.Y, delta.X) * (180.0f / IM_PI);

	//	SDK::FVector2D ret;
	//	ret.X = currentAngles.Pitch + (pitch - currentAngles.Pitch) / smoothness;
	//	ret.Y = SmoothOutYaw(yaw, currentAngles.Yaw, smoothness);
	//	ret.Normalize(); // makes the angles work for Sword With Sauce's angle system

	//	return { ret.X,ret.Y,0 };
	//}
	
#define CONST_RadToUnrRot                                        10430.3783504704527
	SDK::FRotator VectorToRotation(const SDK::FVector& src, const SDK::FVector& dst)
	{
		SDK::FRotator rRotation;
		SDK::FVector delta = dst - src;
		//rRotation.Yaw = atan2(vVector.Y, vVector.X) * CONST_RadToUnrRot;
		//rRotation.Pitch = atan2(vVector.Z, sqrt((vVector.X * vVector.X) + (vVector.Y * vVector.Y))) * CONST_RadToUnrRot;
		float dist = sqrtf(delta.X * delta.X + delta.Y * delta.Y + delta.Z * delta.Z);
		rRotation.Yaw = atan2f(delta.Y, delta.X) * (180.0f / IM_PI);
		rRotation.Pitch = (-((acosf((delta.Z / dist)) * 180.0f / IM_PI) - 90.0f));
		rRotation.Roll = 0;
		
	/*	SDK::FVector2D ret;

		ret.X = rRotation.Pitch;
		ret.Y = rRotation.Yaw;
		ret.Normalize();*/
		//return { ret.X,ret.Y,0 };
		return rRotation;
	}
	SDK::FRotator AimAtVector(SDK::FVector TargetVec, SDK::FVector PlayerLocation)
	{
		/*SDK::FVector AimVec;
		AimVec.X = TargetVec.X - PlayerLocation.X;
		AimVec.Y = TargetVec.Y - PlayerLocation.Y;
		AimVec.Z = TargetVec.Z - PlayerLocation.Z;


		return VectorToRotation(AimVec);*/
	}

	SDK::FVector GetVectorForward(const SDK::FVector& angles)
	{
		float sp, sy, cp, cy;
		float angle;

		angle = angles.Y * (IM_PI / 180.0f);
		sy = sinf(angle);
		cy = cosf(angle);
		angle = -angles.X * (IM_PI / 180.0f);
		sp = sinf(angle);
		cp = cosf(angle);

		return { cp * cy, cp * sy, -sp };
	}

	//SDK::AMec_C* GetClosestEnemy(SDK::FVector& outLocation, int& outId)
	//{
	//	SDK::FVector2D winCenter{ GetSystemMetrics(SM_CXSCREEN),GetSystemMetrics(SM_CYSCREEN) };
	//	auto LP = unrealengine::World->OwningGameInstance->LocalPlayers[0];
	//	SDK::AMec_C* ret = nullptr;
	//	float closestDist = INFINITY;

	//	for (USHORT i = 0; i < unrealengine::World->PersistentLevel->Actors.Num(); i++)
	//	{
	//		auto ent = (SDK::AMec_C*)unrealengine::World->PersistentLevel->Actors[i];
	//		/*if (!ent->K2_IsAlive())
	//			break;*/

	//		SDK::FVector target = ent->Mesh->GetSocketLocation(ent->Mesh->GetBoneName(46));

	//		SDK::FVector2D screenPos;
	//		if (!LP->PlayerController->ProjectWorldLocationToScreen(target, &screenPos, false))
	//			continue;

	//		float dist = winCenter.Distance(screenPos);
	//		if (bFov && dist > Fov)
	//			continue;

	//		if (dist < closestDist)
	//		{
	//			closestDist = dist;
	//			outLocation = target;
	//			outId = ent->Index;
	//			ret = ent;
	//		}
	//	}

	//	return ret;
	//}
};

inline unrealengine* ue = new unrealengine;